BEGIN;

CREATE TABLE IF NOT EXISTS users (
  user_id INTEGER PRIMARY KEY NOT NULL,
  username VARCHAR(50),
  approval_time DATETIME,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

COMMIT;